global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: false
  resolution: 0.5 #0.01
  transform_tolerance: 1.0
  map_type: costmap


  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    inflation_radius: 1.0
